apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-game-app
  labels:
    app: word-game-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: word-game-app
  template:
    metadata:
      labels:
        app: word-game-app
    spec:
      containers:
      - name: word-game-app
        image: word-game-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        env:
        - name: GAME_TITLE
          valueFrom:
            configMapKeyRef:
              name: word-game-config
              key: GAME_TITLE
        - name: GAME_VERSION
          valueFrom:
            configMapKeyRef:
              name: word-game-config
              key: GAME_VERSION
        - name: GAME_DEVELOPER
          valueFrom:
            configMapKeyRef:
              name: word-game-config
              key: GAME_DEVELOPER

